# Generated by Django 4.2.20 on 2025-03-25 12:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('store_type', models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('both', 'Both')], default='retail', max_length=20)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('registration_date', models.DateField()),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('operating_days', models.CharField(choices=[('mon-fri', 'Monday to Friday'), ('mon-sat', 'Monday to Saturday'), ('all', 'All Days'), ('custom', 'Custom Days')], default='mon-sat', max_length=100)),
                ('opening_time', models.TimeField(default='09:00')),
                ('closing_time', models.TimeField(default='21:00')),
                ('number_of_employees', models.IntegerField(default=1)),
                ('store_area', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('has_home_delivery', models.BooleanField(default=False)),
                ('has_online_ordering', models.BooleanField(default=False)),
                ('accepts_insurance', models.BooleanField(default=False)),
                ('inventory_management_system', models.BooleanField(default=False)),
                ('has_pharmacist', models.BooleanField(default=False)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_store', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Store',
                'verbose_name_plural': 'Medical Stores',
                'ordering': ['-created_at'],
            },
        ),
    ]
