# Generated by Django 4.2.20 on 2025-03-26 07:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_reviews', models.IntegerField(default=0)),
                ('address', models.TextField(blank=True, null=True)),
                ('start_time', models.TimeField(default='10:00')),
                ('end_time', models.TimeField(default='18:00')),
                ('working_days', models.CharField(choices=[('custom', 'Custom Days'), ('mon-fri', 'Monday to Friday'), ('mon-sat', 'Monday to Saturday'), ('tue-sun', 'Tuesday to Sunday'), ('mon-sun', 'Monday to Sunday'), ('alternate', 'Alternate Days')], default='mon-fri', max_length=20)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('availability_notes', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('medical_license_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='doctors.specialization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['-created_at'],
            },
        ),
    ]
