# Generated by Django 4.2.20 on 2025-03-26 07:04

from django.db import migrations


def create_specializations(apps, schema_editor):
    Specialization = apps.get_model('doctors', 'Specialization')
    specializations = [
        ('Dermatologist', 'Skin and related disorders'),
        ('Allergist', 'Allergies and immune system disorders'),
        ('Gastroenterologist', 'Digestive system disorders'),
        ('Hepatologist', 'Liver and bile duct disorders'),
        ('Internal Medicine', 'General medical conditions'),
        ('Endocrinologist', 'Hormonal disorders'),
        ('Cardiologist', 'Heart and blood vessels'),
        ('Neurologist', 'Nervous system disorders'),
        ('Osteopathic', 'Musculoskeletal system'),
        ('Pulmonologist', 'Lung and respiratory system'),
        ('General Practitioner', 'Infectious Disease Specialist')
    ]
    
    for name, description in specializations:
        Specialization.objects.create(
            name=name,
            description=description,
            is_active=True
        )

class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_specializations),
    ]