# Generated by Django 4.2.20 on 2025-03-26 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20250326_1234'),
    ]

    operations = [
    ]
