# Generated by Django 4.2.20 on 2025-03-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_medicine_prescribedmedicine_prescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescribedmedicine',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicines',
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='dosage_form',
            field=models.CharField(blank=True, help_text='e.g., Tablet, Capsule, Syrup', max_length=100),
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='generic_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='prescribedmedicine',
            name='strength',
            field=models.CharField(blank=True, help_text='e.g., 500mg, 10mg/5ml', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescribedmedicine',
            name='dosage',
            field=models.CharField(blank=True, help_text='e.g., 1 tablet, 5ml', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescribedmedicine',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g., 5 days, 2 weeks', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescribedmedicine',
            name='frequency',
            field=models.CharField(blank=True, help_text='e.g., 3 times daily, once daily', max_length=100),
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
